### ISSUE TITLE
Add a memory manager

### ISSUE THREAD

**Issue by d4ilyrun** [d4ilyrun/kernel#1]
As stated inside the [README](README.md#things-id-like-to-learnimplement), I'd like to implement a memory manager for my kernel.

## What

The memory manager is responsible for:
* Finding unused physical addresses inside the RAM
* Finding unused virtual address spaces
* Mapping these virtual addresses to the fetched physical pages

These mapped virtual addresses should then be used by a `mmap` like interface to complete the cycle and be able to allocate memory on demand.

> [!NOTE]
>
> As we are still working in kernel mode only, this allocator is destined to only be used inside our kernel's code (`kmalloc`?).
> Once we reach userspace later, another allocator should be written for programs executed in ring 3 (added to the standard library).

## How

From my current understanding, here's what should be added to have a working memory allocator.  
Additional requirements are susceptible to be added later, once I dive deeper into the subject.

### PMM

* Retrieve unused physical pageframes

### MMU

* Activate paging (4.1.2)
* Map virtual addresses to physical pages
  *  Page table
  * Page directories

### VMM

* Detect free/unused virtual address ranges
* Fetch a usable contiguous virtual address range based on size
* Handle memory mapped onto a file (without MAP_ANONYMOUS on Unix) => outside of this issue's scope

## TODO

- [X] Physical Memory Manager #2
- [X] Interface with the MMU
- [X] VMM / Virtual Address Allocator #11

## References

* Intel's manual volume 3: chapter 3-4
* [Memory Management](https://wiki.osdev.org/Memory_management)

**Comment by d4ilyrun** [comment]
Our VMM is still missing a **Virtual Address Allocator**, as such i am reopening this issue.
